# Generated by Django 2.2 on 2019-08-01 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.TextField(verbose_name='Address')),
                ('nit', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_num', models.CharField(max_length=8)),
                ('check_in', models.DateTimeField(verbose_name='Check-in')),
                ('check_out', models.DateTimeField(verbose_name='Check-out')),
                ('total', models.DecimalField(decimal_places=2, max_digits=3)),
                ('status', models.BooleanField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Owner')),
            ],
        ),
    ]
