# Generated by Django 2.2 on 2019-08-01 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
